Repository AY2122S2-CS2103T-T11-2/tp, pull requests merged in 2022-04, with the labels that each got.

#265 FIX UG, ADD ELABORATIONS
  docs/UserGuide.md
Labels: documentation

#278 Branch delete client commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/property/HouseType.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/BuyerCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ClearBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearSellerCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSellerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ListSellerCommandTest.java
  src/test/java/seedu/address/logic/commands/SellerCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddBuyerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/buyer/BuyerTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
  src/test/java/seedu/address/model/seller/SellerTest.java
  src/test/java/seedu/address/testutil/BuyerUtil.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditBuyerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditSellerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/SellerUtil.java
  src/test/java/seedu/address/testutil/TypicalBuyers.java
  src/test/java/seedu/address/testutil/TypicalClients.java
  src/test/java/seedu/address/testutil/TypicalSellers.java
Labels: help wanted

#286 Add more test cases for add property to buy and sell, and delete commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddPropertyToBuyCommand.java
  src/main/java/seedu/address/logic/commands/AddPropertyToSellCommand.java
  src/main/java/seedu/address/model/client/Phone.java
  src/main/java/seedu/address/model/property/HouseType.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPtbCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPtsCommandTest.java
  src/test/java/seedu/address/logic/commands/PropertyCommandsTestUtil.java
  src/test/java/seedu/address/logic/parser/AddPtbCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddPtsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteBuyerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteSellerCommandParserTest.java
  src/test/java/seedu/address/model/property/HouseTypeTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: testing

#301 Add test cases for B/S AddressBook classes
  src/main/java/seedu/address/model/BuyerAddressBook.java
  src/test/java/seedu/address/model/BuyerAddressBookTest.java
  src/test/java/seedu/address/model/SellerAddressBookTest.java
  src/test/java/seedu/address/storage/JsonSerializableBuyerAddressBookTest.java
Labels: testing

#321 Fix DG UML diagrams, use cases and UG appt
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/team/wjunhong.md
Labels: documentation
